version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8181:8080"
    volumes:
      - /jenkins:/var/jenkins_home    # 디렉토리 상황에 맞게 변경
    user: root
    restart: always
    container_name: jenkins
