version: '3'
services:
  jenkins:
    image: custom-jenkins:lts
    ports:
      - "8181:8080"
    volumes:
      - /Users/acacian/jenkins:/var/jenkins_home    # 디렉토리 상황에 맞게 변경
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: always
    container_name: jenkins
