pipeline {
    agent any

    environment {
        IMAGE_NAME = "jenkins/hello-world:lts"
        REGISTRY_URL = "gkehdrn95ctl/jenkins-practice:lts"
        CREDENTIAL_ID = "docker_hub_credentials"

        DOCKERHUB_CREDENTIAL = credentials('docker_hub_credentials')

//        DOCKERHUB_USERNAME = credentials('docker_hub_credentials').username
//        DOCKERHUB_PASSWORD = credentials('docker_hub_credentials').password
        DOCKER_IMAGE = ''
    }

	stages {
		stage("Checkout") {
			steps {
				checkout scm
				echo "image name : $IMAGE_NAME"
				echo "regestiry url : $REGISTRY_URL"
				echo "credential id : $CREDENTIAL_ID"
			}
		}

		stage("Build jar") {
        	steps {
        	    echo 'Build jar'
                sh 'chmod +x gradlew'
                sh './gradlew clean build -b build.gradle'
        	}
        }

        stage("Build image") {
             steps {
                 script {
        	        echo 'Build image'

                    DOCKER_IMAGE = docker.build( IMAGE_NAME, "-f infra/Dockerfile ." )
                 }
             }
        }

        stage("Push image") {
             steps {
                 script {
        	        echo 'Push image'
        	        sh "docker login -u $DOCKERHUB_CREDENTIAL_USR -p $DOCKERHUB_CREDENTIAL_PSW"
                    sh "docker push $REGISTRY_URL"
//                    sh "docker push $DOCKERHUB_CREDENTIAL_USR/$IMAGE_NAME"

//        	        docker.withRegistry( REGISTRY_URL, CREDENTIAL_ID ) {
//        	            DOCKER_IMAGE
//                  }
                 }
             }
        }

        stage("Clean image") {
             steps {
                 script {
        	        echo 'Clean image'
           	        sh 'docker rmi $IMAGE_NAME'
                 }
             }
        }

	}
}