pipeline {
    agent any

    environment {
        imagename = "jenkins/hello-world:lts"
        registryUrl = "gkehdrn95ctl/jenkins-practice:lts"
        registryCredentialId = "docker_hub_credentials"

        DOCKERHUB_USERNAME = "${credentials('docker_hub_credentials').username}"
        DOCKERHUB_PASSWORD = "${credentials('docker_hub_credentials').password}"
        dockerImage = ''
    }

	stages {
		stage("Checkout") {
			steps {
				checkout scm
			}
		}

		stage("Build jar") {
        	steps {
        	    echo 'Build jar'
                sh 'chmod +x gradlew'
                sh './gradlew clean build -b build.gradle'
        	}
        }

        stage("Build image") {
             steps {
                 script {
        	        echo 'Build image'

//                    sh 'docker build -t $imagename -f infra/Dockerfile .'
                    dockerImage = docker.build( imagename, "-f infra/Dockerfile ." )
                 }
             }
        }

        stage("Push image") {
             steps {
                 script {
        	        echo 'Push image'
        	        withCredentials([usernamePassword(credentialsId: 'registryCredentialId', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                        sh "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD"
                    }
                    sh "docker push $DOCKERHUB_USERNAME/$imagename"

//        	        docker.withRegistry( registryUrl, registryCredentialId ) {
//        	            dockerImage
//                  }
                 }
             }
        }

        stage("Clean image") {
             steps {
                 script {
        	        echo 'Clean image'
           	        sh 'docker rmi $imagename'
                 }
             }
        }

	}
}