pipeline {
    agent any

    environment {
        IMAGE_NAME = "jenkins/hello-world:lts"
        REGISTRY_URL = "gkehdrn95ctl/jenkins-practice:lts"
        CREDENTIAL_ID = "docker_hub_credentials"

        CREDENTIAL = credentials("docker_hub_credentials")

//        DOCKERHUB_USERNAME = credentials('docker_hub_credentials').username
//        DOCKERHUB_PASSWORD = credentials('docker_hub_credentials').password
        DOCKER_IMAGE = ''
    }

	stages {
		stage("Checkout") {
			steps {
				checkout scm
				echo '$IMAGE_NAME'
				echo '$REGISTRY_URL'
				echo '$CREDENTIAL_ID'
				echo '$CREDENTIAL'
				echo '$DOCKERHUB_USERNAME'
				echo '$DOCKERHUB_PASSWORD'
			}
		}

		stage("Build jar") {
        	steps {
        	    echo 'Build jar'
                sh 'chmod +x gradlew'
                sh './gradlew clean build -b build.gradle'
        	}
        }

        stage("Build image") {
             steps {
                 script {
        	        echo 'Build image'

                    DOCKER_IMAGE = docker.build( IMAGE_NAME, "-f infra/Dockerfile ." )
                 }
             }
        }

        stage("Push image") {
             steps {
                 script {
        	        echo 'Push image'
        	        withCredentials([usernamePassword(credentialsId: 'CREDENTIAL_ID', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                        sh "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD"
                    }
                    sh "docker push $DOCKERHUB_USERNAME/$IMAGE_NAME"

//        	        docker.withRegistry( REGISTRY_URL, CREDENTIAL_ID ) {
//        	            DOCKER_IMAGE
//                  }
                 }
             }
        }

        stage("Clean image") {
             steps {
                 script {
        	        echo 'Clean image'
           	        sh 'docker rmi $IMAGE_NAME'
                 }
             }
        }

	}
}